name: mlflow-advanced-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - mlflow>=2.10.0
    - scikit-learn>=1.3.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - protobuf>=3.20.0,<4.0.0  # Penting untuk Docker build
    - docker  # Untuk build-docker command